version: "3.1"

services:
  db:
    container_name: mongoDB
    image: mongo:latest
    restart: always
    volumes:
      - ./db_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=${DB_NAME}
    ports:
      - 27017:27017